# Generated by Django 3.1.7 on 2021-03-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20210307_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='create_at',
            field=models.DateField(),
        ),
    ]
