# Generated by Django 3.1.7 on 2021-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20210310_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField()),
                ('budget_for', models.CharField(choices=[('1', 'DAY'), ('1', 'WEEK'), ('1', 'MONTH')], max_length=50)),
                ('deadline', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
